language: java
jdk:
  - openjdk15

script: "./mvnw clean package"


before_install:
  - pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - codecov --file coverage/lcov.info --disable search
